FROM node:16-buster-slim

WORKDIR /app

ADD package.json yarn.lock ./

RUN yarn install --silent

ADD buildDashboardApp.sh ./
ADD public/index.html ./public/
ADD src/App.js src/index.js ./src/

CMD ["/bin/bash", "buildDashboardApp.sh"]