#FROM node:12-buster-slim
FROM ghcr.io/puppeteer/puppeteer:latest

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD 1
ENV DASHBOARD_URL https://raw.githubusercontent.com/pascalw/kindle-dash/main/example/example.png

WORKDIR /app

RUN mkdir -p ./node_modules 

ADD package.json yarn.lock ./

RUN yarn install --silent

ADD screenshot.js makeDashboardImage.sh /app/

CMD ["/bin/bash", "/app/makeDashboardImage.sh"]