FROM node:12-buster-slim

# We don't need the standalone Chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# Install Google Chrome Stable and fonts
# Note: this installs the necessary libs to make the browser work with Puppeteer.
RUN apt-get update && apt-get install curl gnupg -y \
  && curl --location --silent https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update 

RUN apt-get install google-chrome-stable -y --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD 1
ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/google-chrome-stable
ENV DASHBOARD_URL https://raw.githubusercontent.com/pascalw/kindle-dash/main/example/example.png

WORKDIR /app

RUN mkdir -p ./node_modules 

ADD package.json yarn.lock ./

RUN yarn install --silent

ADD screenshot.js makeDashboardImage.sh /app/

CMD ["/bin/bash", "/app/makeDashboardImage.sh"]